app/core/controllers.py
import json
from flask import (
    render_template,
    request,
    Response,
    flash,
    redirect,
    url_for,
    Blueprint
)

from app import csrf
from app.core.models import (
    Venue,
    Artist
)
from app.core.forms import (
    VenueForm,
    ArtistForm,
    ShowForm
)

from app.core.helpers.database import DBApi

core_module = Blueprint('core', __name__, url_prefix='/')


@core_module.route('/')
def index():
    return render_template('pages/home.html')


#  Venues
#  ----------------------------------------------------------------

@core_module.route('/venues')
def venues():
    try:
        data = DBApi.get_venues()
    except Exception:
        flash('Oops something went wrong.', 'error')
        return render_template('pages/home.html')
    return render_template('pages/venues.html', areas=data, count=len(data))


@core_module.route('/venues/search', methods=['POST'])
def search_venues():
    # search on venues with partial string search.
    search_term = request.form.get('search_term', '')
    try:
        response = DBApi.search_venues_or_artists(Venue, search_term)
    except Exception:
        flash('Oops something went wrong.', 'error')
        return render_template('pages/home.html')
    return render_template(
        'pages/search_venues.html',
        results=response,
        search_term=search_term)


@core_module.route('/venues/<int:venue_id>', methods=['GET'])
def show_venue(venue_id):
    # shows the venue page with the given venue_id
    try:
        data = DBApi.get_by_id(Venue, venue_id)
    except Exception:
        flash('Oops something went wrong.', 'error')
        return render_template('pages/home.html')
    return render_template('pages/show_venue.html', venue=data)

#  Create Venue
#  ----------------------------------------------------------------


@core_module.route('/venues/create', methods=['GET'])
def create_venue_form():
    form = VenueForm()
    try:
        form.genres.choices = DBApi.get_genres()
        form.state.choices = DBApi.get_states()
    except Exception:
        flash('Oops something went wrong', 'error')
    return render_template('forms/new_venue.html', form=form)


@core_module.route('/venues/create', methods=['POST'])
def create_venue_submission():
    try:
        form = VenueForm(request.form)
        form.genres.choices = DBApi.get_genres()
        form.state.choices = DBApi.get_states()
        if form.validate():
            DBApi.create(Venue, form)
            flash('Venue ' + form.name.data + ' was successfully listed!')
            return render_template('pages/home.html')
        for error in form.errors:
            error_message = str(form.errors[error][0])
            flash(error.capitalize().replace('_', ' ') + ' - ' + error_message.strip('(\'.,)'), 'error')
    except Exception as e:
        flash('An error occurred. Venue ' + form.name.data + ' could not be listed.', 'error')
    return render_template('forms/new_venue.html', form=form)


@core_module.route('/venues/<int:venue_id>', methods=['DELETE'])
@csrf.exempt
def delete_venue(venue_id):
    try:
        DBApi.delete_venue(venue_id)
    except Exception:
        flash('An error occurred. \nUnable to delete venue!', 'error')
    return render_template('pages/home.html')


#  Artists
#  ----------------------------------------------------------------
@core_module.route('/artists')
def artists():
    try:
        data = DBApi.get_artists()
    except Exception:
        flash('Oops something went wrong.', 'error')
        return render_template('pages/home.html')
    return render_template('pages/artists.html', artists=data, count=len(data))


@core_module.route('/artists/search', methods=['POST'])
def search_artists():
    # Search on artists with partial string search.
    search_term = request.form.get('search_term', '')
    try:
        response = DBApi.search_venues_or_artists(Artist, search_term)
    except Exception:
        flash('Oops something went wrong.', 'error')
        return render_template('pages/home.html')
    return render_template(
        'pages/search_artists.html',
        results=response,
        search_term=search_term)


@core_module.route('/artists/<int:artist_id>')
def show_artist(artist_id):
    # shows the artist page with the given artist_id
    try:
        data = DBApi.get_by_id(Artist, artist_id)
    except Exception:
        flash('Oops something went wrong.', 'error')
        return render_template('pages/home.html')
    return render_template('pages/show_artist.html', artist=data)


#  Update
#  ----------------------------------------------------------------
@core_module.route('/artists/<int:artist_id>/edit', methods=['GET'])
def edit_artist(artist_id):
    try:
        artist = DBApi.get_by_id(Artist, artist_id)
        genre_choices = DBApi.get_genres()
        state_choices = DBApi.get_states()
    except Exception:
        flash('Oops something went wrong.', 'error')
        return render_template('pages/home.html')
    # Prepare the form for editing
    form = ArtistForm()
    form.genres.choices = genre_choices
    form.state.choices = state_choices
    form.name.default = artist['name']
    form.phone.default = artist['phone']
    form.genres.default = artist['genres']
    form.state.default = artist['state']
    form.city.default = artist['city']
    form.facebook_link.default = artist['facebook_link']
    form.image_link.default = artist['image_link']
    form.website.default = artist['website']
    form.seeking_description.default = artist['seeking_description']
    form.seeking_venue.default = artist['seeking_venue']
    form.process()
    return render_template('forms/edit_artist.html', form=form, artist=artist)


@core_module.route('/artists/<int:artist_id>/edit', methods=['POST'])
def edit_artist_submission(artist_id):
    # update existing artist record with ID <artist_id> using
    # the new attributes
    try:
        form = ArtistForm(request.form)
        form.genres.choices = DBApi.get_genres()
        form.state.choices = DBApi.get_states()
        if form.validate_on_submit():
            DBApi.edit(Artist, form, artist_id)
            flash('Artist ' + form.name.data + ' was successfully updated!')
            return redirect(url_for('core.show_artist', artist_id=artist_id))
        for error in form.errors:
            error_message = str(form.errors[error][0])
            flash(
                error.capitalize().replace('_', ' ') + ' - ' + error_message.strip('(\'.,)'), 'error'
            )
    except Exception:
        flash('An error occurred. Artist ' + form.name.data + ' could not be updated.', 'error')

    artist = dict(request.form)
    artist.update({'id': artist_id})
    return render_template('forms/edit_artist.html', form=form, artist=artist)


@core_module.route('/venues/<int:venue_id>/edit', methods=['GET'])
def edit_venue(venue_id):
    try:
        venue = DBApi.get_by_id(Venue, venue_id)
        genre_choices = DBApi.get_genres()
        state_choices = DBApi.get_states()
    except Exception:
        flash('Oops something went wrong.', 'error')
        return render_template('pages/home.html')
    # Prepare the form for editing
    form = VenueForm()
    form.genres.choices = genre_choices
    form.state.choices = state_choices
    form.name.default = venue['name']
    form.phone.default = venue['phone']
    form.address.default = venue['address']
    form.genres.default = venue['genres']
    form.state.default = venue['state']
    form.city.default = venue['city']
    form.facebook_link.default = venue['facebook_link']
    form.image_link.default = venue['image_link']
    form.website.default = venue['website']
    form.seeking_description.default = venue['seeking_description']
    form.seeking_talent.default = venue['seeking_talent']
    form.process()
    return render_template('forms/edit_venue.html', form=form, venue=venue)


@core_module.route('/venues/<int:venue_id>/edit', methods=['POST'])
def edit_venue_submission(venue_id):
    try:
        form = VenueForm(request.form)
        form.genres.choices = DBApi.get_genres()
        form.state.choices = DBApi.get_states()
        if form.validate_on_submit():
            DBApi.edit(Venue, form, venue_id)
            flash('Venue ' + form.name.data + ' was successfully updated!')
            return redirect(url_for('core.show_venue', venue_id=venue_id))
        for error in form.errors:
            error_message = str(form.errors[error][0])
            flash(
                error.capitalize().replace('_', ' ') + ' - ' + error_message.strip('(\'.,)'), 'error'
            )
    except Exception as e:
        flash('An error occurred. Venue ' + form.name.data + ' could not be updated.', 'error')
    venue = dict(request.form)
    venue.update({'id': venue_id})
    return render_template('forms/edit_venue.html', form=form, venue=venue)

#  Create Artist
#  ----------------------------------------------------------------


@core_module.route('/artists/create', methods=['GET'])
def create_artist_form():
    form = ArtistForm()
    form.genres.choices = DBApi.get_genres()
    form.state.choices = DBApi.get_states()
    return render_template('forms/new_artist.html', form=form)


@core_module.route('/artists/create', methods=['POST'])
def create_artist_submission():
    # called upon submitting the new artist listing form
    try:
        form = ArtistForm(request.form)
        form.genres.choices = DBApi.get_genres()
        form.state.choices = DBApi.get_states()
        if form.validate_on_submit():
            DBApi.create(Artist, form)
            flash('Artist ' + form.name.data + ' was successfully listed!')
            return render_template('pages/home.html')
        for error in form.errors:
            error_message = str(form.errors[error][0])
            flash(error.capitalize().replace('_', ' ') + ' - ' + error_message.strip('(\'.,)'), 'error')
    except Exception:

app/templates/forms/edit_artist.html
{% extends 'layouts/main.html' %}
{% block title %}Edit Artist{% endblock %}
{% block content %}
<div class="form-wrapper">
  <form class="form" method="post" action="/artists/{{artist.id}}/edit">
    {{ form.csrf_token }}
    <h3 class="form-heading">Edit artist <em>{{ artist.name }}</em></h3>
    <div class="form-group">
      <label for="name">Name</label>
      {{ form.name(class_ = 'form-control', autofocus = true) }}
    </div>
    <div class="form-group">
      <label>City & State</label>
      <div class="form-inline">
        <div class="form-group">
          {{ form.city(class_ = 'form-control', placeholder='City', autofocus = true) }}
        </div>
        <div class="form-group">
          {{ form.state(class_ = 'form-control', placeholder='State', autofocus = true) }}
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="phone">Phone</label>
      {{ form.phone(class_ = 'form-control', placeholder='xxx-xxx-xxxx', autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="genres">Genres</label>
      <small>Ctrl+Click to select multiple</small>
      {{ form.genres(class_ = 'form-control', placeholder='Genres, separated by commas', id=genres, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="image_link">Image Link</label>
      {{ form.image_link(class_ = 'form-control', placeholder='http://', id=image_link, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="website">Website</label>
      {{ form.website(class_ = 'form-control', placeholder='http://', id=website, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="facebook_link">Facebook Link</label>
      {{ form.facebook_link(class_ = 'form-control', placeholder='http://', id=facebook_link, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="seeking_venue">Seeking Venue</label>
      {{ form.seeking_venue(class_ = 'seeking-checkbox', id=seeking_venue, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="seeking_description">Seeking Description</label>
      {{ form.seeking_description(class_ = 'form-control', placeholder='What sort of talent are you seeking?', id=seeking_description, autofocus = true) }}
    </div>
    <input type="submit" value="Edit Artist" class="btn btn-primary btn-lg btn-block">
  </form>
</div>
{% endblock %}

app/templates/forms/edit_venue.html
{% extends 'layouts/main.html' %}
{% block title %}Edit Venue{% endblock %}
{% block content %}
<div class="form-wrapper">
  <form class="form" method="post" action="/venues/{{venue.id}}/edit">
    {{ form.csrf_token }}
    <h3 class="form-heading">Edit venue <em>{{ venue.name }}</em> <a href="{{ url_for('core.index') }}"
        title="Back to homepage"><i class="fa fa-home pull-right"></i></a></h3>
    <div class="form-group">
      <label for="name">Name</label>
      {{ form.name(class_ = 'form-control', autofocus = true) }}
    </div>
    <div class="form-group">
      <label>City & State</label>
      <div class="form-inline">
        <div class="form-group">
          {{ form.city(class_ = 'form-control', placeholder='City', autofocus = true) }}
        </div>
        <div class="form-group">
          {{ form.state(class_ = 'form-control', placeholder='State', autofocus = true) }}
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="address">Address</label>
      {{ form.address(class_ = 'form-control', autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="phone">Phone</label>
      {{ form.phone(class_ = 'form-control', placeholder='xxx-xxx-xxxx', autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="genres">Genres</label>
      <small>Ctrl+Click to select multiple</small>
      {{ form.genres(class_ = 'form-control', placeholder='Genres, separated by commas', id=genres, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="image_link">Image Link</label>
      {{ form.image_link(class_ = 'form-control', placeholder='http://', id=image_link, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="website">Website</label>
      {{ form.website(class_ = 'form-control', placeholder='http://', id=website, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="facebook_link">Facebook Link</label>
      {{ form.facebook_link(class_ = 'form-control', placeholder='http://', id=facebook_link, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="seeking_talent">Seeking Talent</label>
      {{ form.seeking_talent(class_ = 'seeking-checkbox', id=seeking_talent, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="seeking_description">Seeking Description</label>
      {{ form.seeking_description(class_ = 'form-control', placeholder='What sort of talent are you seeking?', id=seeking_description, autofocus = true) }}
    </div>
    <input type="submit" value="Edit Venue" class="btn btn-primary btn-lg btn-block">
  </form>
</div>
{% endblock %}

app/templates/forms/new_artist.html
{% extends 'layouts/main.html' %}
{% block title %}New Artist{% endblock %}
{% block content %}
<div class="form-wrapper">
  <form method="post" class="form">
    {{ form.csrf_token }}
    <h3 class="form-heading">List a new artist</h3>
    <div class="form-group">
      <label for="name">Name</label>
      {{ form.name(class_ = 'form-control', autofocus = true) }}
    </div>
    <div class="form-group">
      <label>City & State</label>
      <div class="form-inline">
        <div class="form-group">
          {{ form.city(class_ = 'form-control', placeholder='City', autofocus = true) }}
        </div>
        <div class="form-group">
          {{ form.state(class_ = 'form-control', placeholder='State', autofocus = true) }}
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="phone">Phone</label>
      {{ form.phone(class_ = 'form-control', placeholder='xxx-xxx-xxxx', autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="genres">Genres</label>
      <small>Ctrl+Click to select multiple</small>
      {{ form.genres(class_ = 'form-control', placeholder='Genres, separated by commas', id=form.state, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="genres">Image Link</label>
      {{ form.image_link(class_ = 'form-control', placeholder='http://', id=form.state, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="genres">Website</label>
      {{ form.website(class_ = 'form-control', placeholder='http://', id=form.state, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="genres">Facebook Link</label>
      {{ form.facebook_link(class_ = 'form-control', placeholder='http://', id=form.state, autofocus = true) }}
    </div>
    <input type="submit" value="Create Artist" class="btn btn-primary btn-lg btn-block">
  </form>
</div>
{% endblock %}

app/templates/forms/new_show.html
{% extends 'layouts/main.html' %}
{% block title %}New Show Listing{% endblock %}
{% block content %}
  <div class="form-wrapper">
    <form method="post" class="form">
      {{ form.csrf_token }}
      <h3 class="form-heading">List a new show</h3>
      <div class="form-group">
        <label for="artist_id">Artist ID</label>
        <small>ID can be found on the Artist's Page</small>
        {{ form.artist_id(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
        <label for="venue_id">Venue ID</label>
        <small>ID can be found on the Venue's Page</small>
        {{ form.venue_id(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label for="start_time">Start Time</label>
          {{ form.start_time(class_ = 'form-control', placeholder='YYYY-MM-DD HH:MM', autofocus = true) }}
        </div>
      <input type="submit" value="Create Show" class="btn btn-primary btn-lg btn-block">
    </form>
  </div>
{% endblock %}

app/templates/forms/new_venue.html
{% extends 'layouts/main.html' %}
{% block title %}New Venue{% endblock %}
{% block content %}
<div class="form-wrapper">
  <form method="post" class="form">
    {{ form.csrf_token }}
    <h3 class="form-heading">List a new venue <a href="{{ url_for('core.index') }}" title="Back to homepage"><i
          class="fa fa-home pull-right"></i></a></h3>
    <div class="form-group">
      <label for="name">Name</label>
      {{ form.name(class_ = 'form-control', autofocus = true) }}
    </div>
    <div class="form-group">
      <label>City & State</label>
      <div class="form-inline">
        <div class="form-group">
          {{ form.city(class_ = 'form-control', placeholder='City', autofocus = true) }}
        </div>
        <div class="form-group">
          {{ form.state(class_ = 'form-control', placeholder='State', autofocus = true) }}
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="address">Address</label>
      {{ form.address(class_ = 'form-control', placeholder='House-number Street', autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="phone">Phone</label>
      {{ form.phone(class_ = 'form-control', placeholder='xxx-xxx-xxxx', autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="genres">Genres</label>
      <small>Ctrl+Click to select multiple</small>
      {{ form.genres(class_ = 'form-control', placeholder='Genres, separated by commas', id=form.state, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="genres">Image Link</label>
      {{ form.image_link(class_ = 'form-control', placeholder='http://', id=form.state, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="genres">Website</label>
      {{ form.website(class_ = 'form-control', placeholder='http://', id=form.state, autofocus = true) }}
    </div>
    <div class="form-group">
      <label for="genres">Facebook Link</label>
      {{ form.facebook_link(class_ = 'form-control', placeholder='http://', id=form.state, autofocus = true) }}
    </div>
    <input type="submit" value="Create Venue" class="btn btn-primary btn-lg btn-block">
  </form>
</div>
{% endblock %}